services:
  tread_media:
    build:
      context: .
      dockerfile: Dockerfile
    image: tread_media_api
    container_name: tread_media_api
    hostname: tread_media_api
    environment:
      - USER=kevin
      - SHELL=/bin/bash
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - database    
    networks:
      app_net:
        ipv4_address: 172.20.0.2

  database:
    image: postgres:15
    container_name: tread-media-database
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
    networks:
      app_net:
        ipv4_address: 172.20.0.3      


volumes:
    postgres:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"


